version: "1.7"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      BOT_TOKEN: $BOT_TOKEN
      ASSISTANT_NAME: $ASSISTANT_NAME
      SUDO_USERS: $SUDO_USERS
      SESSION_NAME: $SESSION_NAME
      DURATION_LIMIT: $DURATION_LIMIT
      SUPPORT_GROUP: $SUPPORT_GROUP
      UPDATE_CHANNEL: $UPDATE_CHANNEL
      BOT_USERNAME: $BOT_USERNAME
      COMMAND_PREFIXES: $COMMAND_PREFIXES
      PM_PERMIT: $PM_PERMIT
